name: Run Drilling Data Script

on:
  push:
    branches:
      - main  # Run workflow on pushes to the main branch
  schedule:
    - cron: '0 12 * * *'  # Optional: Run daily at 12:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use Python 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run generate_data.py
        run: python generate_data.py

      # Step 5: Upload the generated CSV files as an artifact
      - name: Upload CSV files
        uses: actions/upload-artifact@v3
        with:
          name: drilling-data-csv
          path: data/*.csv  # Adjust the path if the directory is different
